services:
  kn:
    build:
        context: .
        dockerfile: Dockerfile-gpu
    image: kn:v1
    container_name: kn
    ports:
      - "80:80"
    volumes:
      - ./model:/model  # 将主机上的model目录挂载到容器内的/model目录，实现双向访问
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      TZ: "Asia/Shanghai"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    runtime: nvidia   # 如果是旧 Compose 需要
#    restart: always

