services:
  kn:
    image: kn:v1
    container_name: kn
    ports:
      - "81:80"
    volumes:
      - ./model:/model  # 将主机上的model目录挂载到容器内的/model目录，实现双向访问
    
    # 启用GPU支持 - 使用device属性而不是deploy
    devices:
      - "nvidia.com/gpu=all"
#    restart: always
  environment:
    TZ: "Asia/Shanghai"
    NVIDIA_VISIBLE_DEVICES: all
    CUDA_VISIBLE_DEVICES: 0
networks:
  default:
    external: true
    name: nginx_default

