FROM modelscope-registry.cn-hangzhou.cr.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.4.0-py311-torch2.8.0-1.31.0-LLM
LABEL authors="weiii"
RUN pip install Flask==3.1.1  -i https://mirrors.aliyun.com/pypi/simple/
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
COPY . .
RUN chmod +x main.py
EXPOSE 80
CMD ["python", "main.py"]

